name: release

on:
  push:
    branches:
      - 'main'

concurrency:
  group: release-${{ github.ref }}

env:
  VSCE_PAT: ${{ secrets.AZURE_VSCODE_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: clone
        uses: actions/checkout@v4

      - name: prepare
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: setup
        run: yarn

      - name: package
        run: yarn vsce:package

      - name: publish
        run: yarn vsce:publish
